import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    display: "flex",
    paddingTop: 50,
    paddingHorizontal: 15,
    backgroundColor: "#ffffff",
  },
  button: {
    borderRadius: 10,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#f0f0f0",
    padding: 5,
  },
  pressedButton: {
    backgroundColor: "#8a8a8a",
  },
  pressedButtonDark: {
    backgroundColor: "#555555",
  },
  darkButton: {
    backgroundColor: "#333333",
  },
  buttonText: {
    fontSize: 16,
    padding: 10,
    textAlign: "center",
  },
  darkContainer: {
    backgroundColor: "#1e1e1e",
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 15,
  },
  list: {
    paddingBottom: 20,
    paddingTop: 10,
  },
  card: {
    backgroundColor: "#f2f2f2",
    padding: 15,
    borderRadius: 10,
    marginBottom: 15,
  },
  darkCard: {
    backgroundColor: "#333333",
  },
  image: {
    width: "100%",
    height: 300,
    borderRadius: 8,
    marginBottom: 10,
  },
  title: {
    fontSize: 18,
    fontWeight: "bold",
    marginBottom: 5,
  },
  description: {
    fontSize: 14,
  },
  darkText: {
    color: "#ffffff",
  },
  settingsContainer: {
    marginTop: 20,
    marginHorizontal: 10,
  },
  settingsTitle: {
    fontSize: 22,
    fontWeight: "bold",
    marginBottom: 20,
  },
  settingRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  settingText: {
    fontSize: 16,
  },
  photoButton: {
    padding: 10,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: "#007bff",
    borderRadius: 5,
    alignItems: "center",
  },
  choosedImage: {
    width: "100%",
    height: 200,
    marginTop: 10,
    marginBottom: 10,
    borderRadius: 10,
  },
  textInput: {
    width: "100%",
    padding: 8,
    marginBottom: 10,
    borderWidth: 1,
    borderRadius: 10,
  },
  controlButton: {
    padding: 10,
    marginTop: 10,
    marginBottom: 10,
    borderColor: "#808080",
    borderWidth: 2,
    alignItems: "flex-start",
  },
  deleteCard: {
    flexDirection: "row",
    justifyContent: "space-between",
    padding: 15,
  },
  deleteContainerInfo: {
    flexDirection: "column",
  },
  dropdownButton: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "25%",
    padding: 10,
    borderWidth: 1,
    borderRadius: 5,
    backgroundColor: "#eee",
  },
  dropdownList: {
    borderWidth: 1,
    borderColor: "#ccc",
    marginTop: 5,
    borderRadius: 5,
  },
  dropdownWrapper: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 9999,
    alignItems: "center",
  },
  overlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0,0,0,0.3)",
  },
  dropdownBox: {
    width: "40%",
    height: "25%",
    right: "30%",
    top: "12%",
    backgroundColor: "white",
    borderRadius: 15,
    padding: 15,
    elevation: 10,
    shadowColor: "#000",
    shadowOpacity: 0.3,
    shadowRadius: 10,
  },
  item: {
    paddingVertical: 10,
    fontSize: 16,
  },
  pickerContainer: {
    borderWidth: 1,
    borderColor: "#ccc",
    borderRadius: 6,
    width: "100%",
  },
  picker: {
    height: 50,
    width: "10%",
  },
  settingColumn: {
    marginBottom: 20,
  },
  modalContent: {
    width: "85%",
    backgroundColor: "white",
    borderRadius: 20,
    padding: 20,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  modalOverlay: {
    flex: 1,
    zIndex: 9999,
    backgroundColor: "rgba(0,0,0,0.3)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalImage: {
    width: 200,
    height: 150,
    resizeMode: "contain",
    marginBottom: 15,
  },
  modalTitle: {
    fontSize: 22,
    fontWeight: "bold",
    marginBottom: 10,
  },
  modalDescription: {
    fontSize: 16,
    textAlign: "center",
    color: "#444",
    marginBottom: 20,
  },
  modalButton: {
    width: "100%",
  },
  authContainer: {
    flex: 1,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 50,
  },
  authButton: {
    borderRadius: 15,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "dodgerblue",
    paddingVertical: 5,
    paddingHorizontal: 110,
  },
  authText: {
    fontSize: 16,
    padding: 10,
    textAlign: "center",
    color: "white",
  },
  logoutButton: {
    marginTop: 10,
    marginBottom: 10,
    borderColor: "red",
    padding: 10,
    borderWidth: 1,
    borderRadius: 10,
  },
});
